return {
    -- 逻辑帧率
    LOGIC_FPS = 30,
    MAIN_TURRET_MIN_ATK_DISTANCE = 40,
    ENEMY_GENERATE_CENTER_DISTANCE = 70,
    ENEMY_ATK_MAX_DISTANCE = 140,
    ENEMY_ANGULAR_SPEED_RATE = 5,
    GLOBAL_BASE_HEIGHT = 80,
    ENEMY_UNIT_MAX_NUM = 10,
    CAMERA_ADSORBED_DISTANCE = 20,

    TURRET_AUTO_ATK_SCAN_INTERVAL = 60,

    --通用界面事件
    UI_SHOW_LOADING_EVENT = "UI_EVENT_SHOW_LOADING",
    UI_HIDE_LOADING_EVENT = "UI_EVENT_HIDE_LOADING",
    UI_SHOW_MAIN_MENU_EVENT = "UI_EVENT_SHOW_MAIN_MENU",
    UI_HIDE_MAIN_MENU_EVENT = "UI_EVENT_HIDE_MAIN_MENU",
    UI_SHOW_HUD_EVENT = "UI_EVENT_SHOW_HUD",
    UI_HIDE_HUD_EVENT = "UI_EVENT_HIDE_HUD",


    --主菜单界面事件常量
    UI_CONTINUE_GAME_EVENT = "UI_EVENT_CONTINUE_GAME",
    UI_NEW_GAME_EVENT = "UI_EVENT_NEW_GAME",
    UI_ABOUT_EVENT = "UI_EVENT_ABOUT",
    UI_SETTINGS_EVENT = "UI_EVENT_SETTINGS",
    UI_GAME_STATS_EVENT = "UI_EVENT_GAME_STATS",

    --设置界面事件
    UI_VFX_SETTING_SWITCH_EVENT = "UI_EVENT_VFX_SETTING_SWITCH",
    UI_AD_SETTING_SWITCH_EVENT = "UI_EVENT_AD_SETTING_SWITCH",
    UI_COMPONENT_CACHE_SETTING_SWITCH_EVENT = "UI_EVENT_COMPONENT_CACHE_SETTING_SWITCH",

    UI_HIDE_SETTINGS_EVENT = "UI_EVENT_HIDE_SETTINGS",
    UI_HIDE_STATS_EVENT = "UI_EVENT_HIDE_GAME_STATS",

    UI_BRIDGE_SET_VFX_SETTING_TEXT = "UI_BRI_1",
    UI_BRIDGE_SET_AD_SETTING_TEXT = "UI_BRI_2",
    UI_BRIDGE_SET_CACHE_SETTING_TEXT = "UI_BRI_11",
    UI_BRIDGE_SET_GAME_STATS_TEXT = "UI_BRI_3",


    --提示界面事件
    UI_SHOW_DELETE_ARCHIVE_EVENT = "UI_EVENT_SHOW_DELETE_ARCHIVE_NOTICE",
    UI_HIDE_DELETE_ARCHIVE_EVENT = "UI_EVENT_HIDE_DELETE_ARCHIVE_NOTICE",
    UI_CONFIRM_DELETE_ARCHIVE_EVENT = "UI_EVENT_CONFIRM_DELETE_ARCHIVE",
    UI_CANCEL_DELETE_ARCHIVE_EVENT = "UI_EVENT_CANCEL_DELETE_ARCHIVE",


    --通用全局事件
    --相机移动事件
    UI_CAMERA_MOVE_EVENT = "UI_BRI_4",
    UI_CAMERA_MOVE_STOP_EVENT = "UI_EVENT_CAMERA_MOVE_STOP",

    --创建连接特效

    BRIDGE_CREATE_LASER_EFFECT_EVENT = "GLOBAL_BRI_1",
    BRIDGE_CREATE_LINKED_EFFECT_EVENT = "GLOBAL_BRI_2",

    -- UI_CAMERA_ZOOM_EVENT = "UI_BRI_5",
    -- UI_CAMERA_ZOOM_STOP_EVENT = "UI_EVENT_CAMERA_ZOOM_STOP"

    -- hud
    UI_BRIDGE_SET_TARGET_INFO = "UI_BRI_5",
    UI_BRIDGE_SET_CURSOR_STATUS = "UI_BRI_6",
    UI_BRIDGE_UPDATE_CAMERA_POS = "UI_BRI_7",
    UI_BRIDGE_SET_SELF_INFO = "UI_BRI_8",
    UI_BRIDGE_SET_MATRIX_INFO = "UI_BRI_9",
    UI_BRIDGE_SET_AUTO_AIM_STATUS = "UI_BRI_10",
    UI_BRIDGE_SET_BULLET_LOAD_PROGRESS = "UI_BRI_12",
    UI_BRIDGE_SET_RAPID_BULLET_DATA = "UI_BRI_13",
    UI_BRIDGE_SET_RAPID_BULLET_PROGRESS = "UI_BRI_14",

    UI_RAPID_ATTACK_EVENT = "UI_EVENT_RAPID_ATTACK",
    UI_SWITCH_AUTO_AIM_STATUS_EVENT = "UI_EVENT_SWITCH_AUTO_AIM_STATUS",

    --HUD status enum
    ---@enum hudStatus
    cursorStatusEnum = {
        NORMAL = "NORMAL",
        LOCKED = "LOCKED",
        WARN = "WARN",
        URGENT = "URGENT"
    }
}
